import "./globals.css";
import type { Metadata } from "next";
import FlyonuiScript from "./flyonui-script";
import { Providers } from "@/redux/provider";
import { Geist, Geist_Mono } from "next/font/google";
import ThemeWrapper from "@/components/Layout-Components/ThemeWrapper";
import ThemeInitializer from "@/components/Layout-Components/ThemeInitializer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="referrer" content="origin" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <ThemeInitializer />
          <ThemeWrapper>
            <div>
              {children}
            </div>
            <FlyonuiScript />
          </ThemeWrapper>
        </Providers>
      </body>
    </html>
  );
}
